### ISSUE TITLE
Node 8 and require-dir aren't very good friends

### ISSUE THREAD

**Issue by Dotpeach** [cleverage/garden-starter-kit#139]
Hi there ! 
Well, that's not a real starter kit issue, but just in case someone has to upgrade **node to its 8 version**, you might encounter this error : 
> [YOURPROJECT]/node_modules/require-dir/index.js:97
>             if (!require.extensions.hasOwnProperty(ext)) {
>                                     ^
> 
> TypeError: require.extensions.hasOwnProperty is not a function

Fixed it with something I found around here : 
https://github.com/aseemk/requireDir/pull/46/files
(just replace `if (!require.extensions.hasOwnProperty(ext)) {` with `if (!Object.prototype.hasOwnProperty.call(require.extensions, ext))` and all should build perfectly)

Dunno if this fix works in lower version or not so… A pull request doesn't seem to be a very good idea. :/ 

I guess @ryuran will know if there is a real solution to prevent this from happening (or not).

**Comment by ryuran** [comment]
Yes, I do, I will remove dependency to require-dir (fixed in v3-alpha)

**Comment by piouPiouM** [comment]
@ryuran it's works well with 0.3.2 (see https://github.com/aseemk/requireDir/pull/46)

**Comment by ryuran** [comment]
Yes, it's a it's a known problem, requireDir  0.3.2 fix it.
